name: lxcfs docker publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:

  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]


defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  generate-jobs:
    name: lxcfs
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix:
        include:
          -
            name: lxcfs
            image: dongjiang1989/lxcfs:v6.0.3
            file: ./hack/build/Dockerfile.lxcfs
            platforms: linux/amd64,linux/arm64
          -
            name: lxcfs-webhook
            image: dongjiang1989/lxcfs-webhook:latest
            file: ./hack/build/Dockerfile.webhook
            platforms: linux/amd64,linux/arm64

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3 
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Registry
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.image }}
      - name: Test ${{ matrix.name }}
        run: |
          docker pull ${{ matrix.image}}
          docker image inspect ${{ matrix.image}}
